name: FedSA-LoRA-DP-py310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==1.4.0
      - accelerate==1.10.1
      - array-record==0.8.1
      - astunparse==1.6.3
      - attrs==23.1.0
      - bleach==6.2.0
      - cachetools==5.5.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.4
      - decorator==5.2.1
      - dm-tree==0.1.8
      - docstring-parser==0.17.0
      - dp-accounting==0.4.3
      - einops==0.8.1
      - etils==1.13.0
      - exceptiongroup==1.1.3
      - farmhashpy==0.4.0
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.6.0
      - gin-config==0.5.0
      - google-api-core==2.25.2
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - google-vizier==0.1.11
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - grpcio-tools==1.62.3
      - h5py==3.14.0
      - hf-xet==1.1.10
      - httplib2==0.31.0
      - huggingface-hub==0.35.3
      - idna==3.10
      - immutabledict==2.2.5
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jax==0.4.14
      - jaxlib==0.4.14
      - jinja2==3.1.6
      - joblib==1.5.2
      - kaggle==1.7.4.5
      - keras==2.14.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lxml==6.0.2
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauth2client==4.1.3
      - oauthlib==3.3.1
      - opacus==1.4.0
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==22.0
      - pandas==1.5.3
      - patsy==1.0.1
      - peft==0.17.1
      - pillow==11.3.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - portpicker==1.6.0
      - promise==2.3
      - proto-plus==1.26.1
      - protobuf==4.21.12
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.10
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.9.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - seqeval==1.2.2
      - simple-parsing==0.1.7
      - six==1.17.0
      - sqlalchemy==1.4.20
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-compression==2.14.0
      - tensorflow-datasets==4.9.9
      - tensorflow-estimator==2.14.0
      - tensorflow-federated==0.64.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - tensorflow-model-optimization==0.7.5
      - tensorflow-privacy==0.8.12
      - tensorflow-probability==0.22.1
      - tensorflow-text==2.14.0
      - termcolor==3.1.0
      - text-unidecode==1.3
      - tf-keras==2.15.0
      - tf-models-official==2.14.2
      - tf-slim==1.1.0
      - threadpoolctl==3.6.0
      - timm==0.9.16
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tqdm==4.67.1
      - transformers==4.30.0
      - triton==2.1.0
      - typing-extensions==4.5.0
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - zipp==3.23.0
prefix: /home/miyata/anaconda3/envs/FedSA-LoRA-DP-py310
